// flow-typed signature: 69aa6bfa084be1d2c47683946f1f353f
// flow-typed version: <<STUB>>/boom_v^7.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boom/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boom/lib/index.js' {
  declare module.exports: $Exports<'boom/lib/index'>;
}
