// flow-typed signature: 3ba4d569035187903fec1cb4ca98dd3b
// flow-typed version: <<STUB>>/module-alias_v^2.1.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'module-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'module-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'module-alias/register' {
  declare module.exports: any;
}

declare module 'module-alias/test/src/bar/baz/index' {
  declare module.exports: any;
}

declare module 'module-alias/test/src/foo/index' {
  declare module.exports: any;
}

declare module 'module-alias/test/src/node_modules_custom/some-module/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'module-alias/index' {
  declare module.exports: $Exports<'module-alias'>;
}
declare module 'module-alias/index.js' {
  declare module.exports: $Exports<'module-alias'>;
}
declare module 'module-alias/register.js' {
  declare module.exports: $Exports<'module-alias/register'>;
}
declare module 'module-alias/test/src/bar/baz/index.js' {
  declare module.exports: $Exports<'module-alias/test/src/bar/baz/index'>;
}
declare module 'module-alias/test/src/foo/index.js' {
  declare module.exports: $Exports<'module-alias/test/src/foo/index'>;
}
declare module 'module-alias/test/src/node_modules_custom/some-module/index.js' {
  declare module.exports: $Exports<'module-alias/test/src/node_modules_custom/some-module/index'>;
}
